### ISSUE TITLE
unmatched dependencies when installing the latest "@angular/animations" as defined in package.json

### ISSUE THREAD

**Issue by aelsaman** [designcourse/ionic-3-onboard-animation-example#1]
Hello , 
first of all thanks for the ionic 3 example,  this is useful. However, I tried to pull locally and run "npm install" but I ran into issues with the dependencies that prevents the application from working normally. Here is the message I got on my cli:

UNMET PEER DEPENDENCY @angular/core@4.1.3

npm ERR! peer dep missing: @angular/core@4.2.4, required by @angular/animations@4.2.4
npm ERR! missing: esprima-fb@~3001.0001.0000-dev-harmony-fb, required by es3ify@0.1.4

------------------------------------
I noticed in your package.json that you are requesting the latest version of angular/animation ( currently it is 4.2.x ) which in turns requires the latest version of angular/core whilst the app itself is depending on a strict older version of angular/core "4.1.3". and that causes a conflict ( as far as I understand ) as posted above.

I managed to fix this by modifying the main package.json before running "npm install" by strictly require a strict version of angular/animation instead of the latest as below:

`"dependencies": {
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/core": "3.10.2",
    "@ionic-native/splash-screen": "3.10.2",
    "@ionic-native/status-bar": "3.10.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.4.2",
    "ionicons": "3.0.0",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.12"
  }`
 
Thanks

**Comment by theHellyar** [comment]
Thanks.. he should really change that perhaps do a pull request with that change. 

Also...perhaps its my box but the "Error: Cannot read property 'replace' of undefined" comes up for me so the iOS-sim locally installed should be updated to the latest  ( cd into the platforms/ios/cordova/node_modules and npm install iOS-sim@latest for the fix)
